version: 1
formatters:
  simple:
    format: '%(levelname)s - %(asctime)s - %(message)s'
  extended:
    format: "%(levelname)s %(asctime)s,%(msecs)d [Process %(process)d %(processName)s %(threadName)s] [%(module)s %(funcName)s]: %(message)s "

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: extended
    filename: delta.log


loggers:
  simple:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

  DB:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]