version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  extended:
    format: "%(levelname)s %(asctime)s,%(msecs)d [Process %(process)d %(processName)s %(threadName)s] [%(module)s %(funcName)s]: %(message)s "

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: extended
    stream: ext://sys.stdout

loggers:
  simple:
    level: DEBUG
    handlers: [console]
    propagate: no

  DB:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]